### ISSUE TITLE
可以看看你的前端代码吗

### ISSUE THREAD

**Issue by keepaliveon** [Hill1126/PsychologicalCounselingPlatform#1]
这位同学，看了你的代码十分想了解你这个项目，可以把前端也开源一下吗

**Comment by Hill1126** [comment]
> 这位同学，看了你的代码十分想了解你这个项目，可以把前端也开源一下吗

非常抱歉， 这只是一个简单的毕业设计项目，同时前端代码不是我负责的，所以我也不确定他是否开源了，到时我们组的成员有开源并且你如果还有需要，我会及时告知给你

**Comment by keepaliveon** [comment]
> > 这位同学，看了你的代码十分想了解你这个项目，可以把前端也开源一下吗
> 
> 非常抱歉， 这只是一个简单的毕业设计项目，同时前端代码不是我负责的，所以我也不确定他是否开源了，到时我们组的成员有开源并且你如果还有需要，我会及时告知给你



> > 这位同学，看了你的代码十分想了解你这个项目，可以把前端也开源一下吗
> 
> 非常抱歉， 这只是一个简单的毕业设计项目，同时前端代码不是我负责的，所以我也不确定他是否开源了，到时我们组的成员有开源并且你如果还有需要，我会及时告知给你

感谢你的回复，如何可能的话，还是希望能看到完整的代码好学习一下的
